advert/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from views import AdvertAllView, AdvertOneView, AdvertFilterPriceUPView, AdvertFilterPriceDownView, \
    AdvertFilterPropertyTypeUPView, AdvertFilterPropertyTypeDownView
from views import AdvertUpdateView, successful, AdvertCabinetView, clear_database, AdvertAddView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^all/$', AdvertAllView.as_view(), name='all'),
    url(r'^(?P<pk>\d+)/$', AdvertOneView.as_view(), name='one'),
    url(r'^clear/$', clear_database, name='clear_database'),
    url(r'^filter_price_up/$', AdvertFilterPriceUPView.as_view(), name='filter_price_up'),
    url(r'^filter_price_down/$', AdvertFilterPriceDownView.as_view(), name='filter_price_down'),
    url(r'^filter_property_type_up/$', AdvertFilterPropertyTypeUPView.as_view(), name='filter_property_type_up'),
    url(r'^filter_property_type_down/$', AdvertFilterPropertyTypeDownView.as_view(), name='filter_property_type_down'),
    url(r'^add/$', AdvertAddView.as_view(), name='add'),
    url(r'^update/(?P<pk>\d+)/$', AdvertUpdateView.as_view(), name='update'),
    url(r'^successful/',  successful, name='successful')
    # url(r'^add/$', AdvertAddView.as_view(), name='add'),

    # url(r'^add/$', model_form_upload, name='add'),
]

blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from blog.views import blog_one, add_comment
from blog.views import BlogAllView

urlpatterns = [
    url(r'^all/$', BlogAllView.as_view(), name='all'),
    url(r'^(?P<pk>[0-9]+)/$', blog_one, name='one'),
    url(r'^add_comment/(?P<pk>[0-9]+)$', add_comment, name='add_comment',)
]

rest_brd/urls.py
# -*- coding: utf-8 -*-
"""rest_brd URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin


from django.conf.urls import include, url
from django.contrib import admin
from auth.views import signup
from django.contrib.auth.views import login, logout
from advert.views import successful
from django.conf import settings
from django.conf.urls.static import static
from advert.views import AdvertCabinetView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^advert/', include('advert.urls', namespace='advert')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^signup/$', signup, name='signup'),
    url(r'^login/$', login, {'template_name': 'auth/login.html'}, name='login', ),
    url(r'^logout/$', logout, {'template_name': 'auth/logout.html', 'next_page': '/advert/all/'}, name='logout'),
    url(r'^cabinet/',  AdvertCabinetView.as_view(), name='cabinet'),
    # url(r'^photos/', include('photos.urls', namespace='photos')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

advert/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# import os
from django.db import models
from django.contrib.auth.models import User
from imagekit.models.fields import ImageSpecField
from imagekit.processors import ResizeToFill
from django_resized import ResizedImageField


class Advert(models.Model):
    class Meta:
        ordering = ['-advert_date_pub', ]
        verbose_name = 'объявление'
        verbose_name_plural = 'объявления'

    PROPERTY_TYPE = (
        (20, 'база отдыха'),
        (40, 'дача'),
        (60, 'дом (частный сектор)'),
        (80, 'квартира'),
        (100, 'комната'),
        (120, 'коттедж'),
        (140, 'отель'),
        (160, 'пансионат'),
        (180, 'санаторий'),
    )

    DISTRICT = (
        (20, '8 марта'),
        (40, 'азмол'),
        (60, 'акз'),
        (80, 'верховая'),
        (100, 'военный городок'),
        (120, 'дачи'),
        (140, 'колония'),
        (160, 'коса ближняя'),
        (180, 'коса средняя '),
        (200, 'коса дальняя '),
        (220, 'курорт'),
        (240, 'лиски'),
        (260, 'макорты'),
        (280, 'нагорная часть'),
        (300, 'пески'),
        (320, 'ртс'),
        (340, 'слободка'),
        (360, 'стекловолокно'),
        (380, 'третий пляж'),
        (400, 'центр'),
    )

    ROOMS = (
        (20, 'одна комната',),
        (40, 'две комнаты',),
        (60, 'три комнаты',),
        (80, 'четыре и более',),
    )

    advert_name = models.CharField(max_length=65, verbose_name='заголовок', )
    advert_content = models.TextField(max_length=1500, blank=True, verbose_name='текст описания', )
    advert_district = models.PositiveSmallIntegerField(choices=DISTRICT, db_index=True, blank=True, null=True,
                                                       verbose_name='район города', )
    advert_property_type = models.PositiveSmallIntegerField(choices=PROPERTY_TYPE, db_index=True, default=4,
                                                            verbose_name='объект недвижимости', )
    advert_room = models.PositiveSmallIntegerField(choices=ROOMS, db_index=True, blank=True, null=True,
                                                   verbose_name='количество комнат', )
    advert_seat = models.DecimalField(db_index=True, max_digits=2, decimal_places=0, blank=True, null=True,
                                      verbose_name='количество спальных мест', )
    advert_price_from = models.DecimalField(max_digits=5, decimal_places=0, db_index=True, default=100,
                                            verbose_name='цена', )
    advert_price_to = models.DecimalField(max_digits=5, decimal_places=0, blank=True, null=True,
                                          verbose_name='цена до (если несколько вариантов)', )
    advert_address = models.CharField(max_length=100, blank=True, verbose_name='адрес', )
    advert_telephone = models.CharField(default='4535345', max_length=18, verbose_name='телефон', )
    advert_conditioner = models.BooleanField(default=False, verbose_name='кондиционер', )
    advert_tv = models.BooleanField(default=False, verbose_name='телевизор', )
    advert_shower = models.BooleanField(default=False, verbose_name='душ', )
    advert_wi_fi = models.BooleanField(default=False, verbose_name='wi-fi', )
    advert_food = models.BooleanField(default=False, verbose_name='питание', )
    advert_animals = models.BooleanField(default=False, verbose_name='заселение с животными', )
    advert_parking = models.BooleanField(default=False, verbose_name='автостоянка', )
    advert_balcony = models.BooleanField(default=False, verbose_name='балкон', )
    advert_satellite_tv = models.BooleanField(default=False, verbose_name='спутниковое TV', )
    advert_playground = models.BooleanField(default=False, verbose_name='детская площадка', )
    advert_washer = models.BooleanField(default=False, verbose_name='стиральная машинка', )
    advert_brazier = models.BooleanField(default=False, verbose_name='мангал', )
    advert_author = models.CharField(max_length=50, verbose_name='ваше имя', blank=True, )
    advert_views = models.PositiveIntegerField(default=0, verbose_name='количество просмотров', )
    advert_like = models.PositiveIntegerField(default=0, verbose_name='понравилось', )
    advert_dislike = models.PositiveIntegerField(default=0, verbose_name='не понравилось', )
    advert_date_pub = models.DateTimeField(auto_now_add=True, auto_now=False, db_index=True,
                                           verbose_name='дата публикации', )
    advert_date_update = models.DateTimeField(auto_now_add=False, auto_now=True, db_index=True,
                                              verbose_name='дата редактирования', )
    advert_title = models.TextField(max_length=75, verbose_name='Title', blank=True, )
    advert_descriptions = models.TextField(max_length=200, verbose_name='Descriptions', blank=True, )
    advert_keywords = models.TextField(max_length=150, verbose_name='Keywords', blank=True, )
    advert_slug = models.SlugField(verbose_name='URL', blank=True, )
    advert_user = models.ForeignKey(User, verbose_name='автор', )
    advert_active = models.BooleanField(default=True, db_index=True, verbose_name='объявление активное', )


class Photo(models.Model):
    class Meta:
        ordering = ['-photo_date_pub']
        verbose_name = 'фото'
        verbose_name_plural = 'фотки'

    advert = models.ForeignKey(Advert, null=True)
    photo_origin = ResizedImageField(upload_to='uploaded_photo/%Y/%m/%d/', size=[1280, 720], quality=80,
                                     db_index=True, )
    photo_350 = ImageSpecField([ResizeToFill(350, 250)],
                               source='photo_origin',
                               format='JPEG',
                               options={'quality': 75}
                               )
    photo_240 = ImageSpecField([ResizeToFill(240, 130)],
                               source='photo_origin',
                               format='JPEG',
                               options={'quality': 75}
                               )
    photo_date_pub = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name='дата публикации', )
    photo_date_update = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name='дата редактирования', )

























    # advert_photo = models.ImageField(upload_to='uploaded_photo_user/%Y/%m/%d/', height_field=500, width_field=500, )
    # advert_photo_300 = ImageSpecField([ResizeToFill(300, 300)], source='advert_photo', format='JPEG',
    #                                   options={'quality': 95})
    # advert_photo_140 = ImageSpecField([ResizeToFill(140, 140)], source='advert_photo2', format='JPEG',
    #                                   options={'quality': 95})
    # advert_photo_80 = ImageSpecField([ResizeToFill(80, 80)], source='advert_photo2', format='JPEG',
    #                                   options={'quality': 95})
    # advert_email = models.EmailField(max_length=100, blank=True, verbose_name='email', )



    # advert_user = models.ForeignKey(User, verbose_name='автор', editable=False)

    # def __unicode__(self):
    #     return self.advert_name


    # class AdvertPhoto(models.Model):
    #     image_height = models.PositiveIntegerField(null=True, blank=True, editable=False, default="500")
    #     image_width = models.PositiveIntegerField(null=True, blank=True, editable=False, default="500")
    #     advert_photo = models.ImageField(upload_to='uploaded_photo_user/%Y/%m/%d/',
    #                                      height_field='image_height', width_field='image_width', )
    #     advert_photo_300 = ImageSpecField([ResizeToFill(300, 300)], source='advert_photo', format='JPEG',
    #                                       options={'quality': 95})

advert/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from models import Advert, Photo



class AdvertForm(ModelForm):
    class Meta:
        model = Advert
        fields = ['advert_name',
                  'advert_content',
                  'advert_district',
                  'advert_property_type',
                  'advert_room',
                  'advert_seat',
                  'advert_price_from',
                  'advert_price_to',
                  'advert_address',
                  'advert_telephone',
                  'advert_conditioner',
                  'advert_tv',
                  'advert_shower',
                  'advert_wi_fi',
                  'advert_food',
                  'advert_animals',
                  'advert_parking',
                  'advert_balcony',
                  'advert_satellite_tv',
                  'advert_playground',
                  'advert_washer',
                  'advert_brazier',
                  'advert_author',
                  ]


# class PhotoForm(ModelForm):
#     class Meta:
#         model = Photo
#         fields = ['photo_origin']

class PhotoForm(ModelForm):
    class Meta:
        model = Photo
        fields = ['photo_origin']

advert/templates/include/advert_icons.html
{% load staticfiles %}

{% if advert.advert_tv %}
    <div class="fa fa-television" aria-hidden="true" title="телевизор"></div>
{% endif %}
{% if advert.advert_wi_fi %}
    <div class="fa fa-wifi" aria-hidden="true" title="Wi-Fi"></div>
{% endif %}
{% if advert.advert_food %}
    <div class="fa fa-cutlery" aria-hidden="true" title="питание на территории"></div>
{% endif %}
{% if advert.advert_animals %}
    <div class="fa fa-paw" aria-hidden="true" title="размещение с животными"></div>
{% endif %}
{% if advert.advert_parking %}
    <div class="fa fa-car" aria-hidden="true" title="автостоянка"></div>
{% endif %}
{% if advert.advert_parking %}
    <div class="fa fa-shower" aria-hidden="true" title="душ"></div>
{% endif %}
{% if advert.advert_balcony %}
    <img class="balcony" aria-hidden="true" src="{% static 'icons/balcony.svg' %}" title="балкон">
{% endif %}
{% if advert.advert_washer %}
    <img class="washing-machine" aria-hidden="true" src="{% static 'icons/washing-machine.svg' %}" title="стиральная машинка">
{% endif %}
{% if advert.advert_conditioner %}
    <img class="conditioner" aria-hidden="true" src="{% static 'icons/conditioner.svg' %}" title="кондиционер">
{% endif %}
{% if advert.advert_playground %}
    <img class="playground" aria-hidden="true" src="{% static 'icons/playground.svg' %}" title="детская площадка">
{% endif %}
{% if advert.advert_brazier %}
    <img class="brazier" aria-hidden="true" src="{% static 'icons/brazier.svg' %}" title="мангал">
{% endif %}
{% if advert.advert_satellite_tv %}
    <img class="satellite_tv" aria-hidden="true" src="{% static 'icons/satellite.svg' %}" title="спутниковое TV">
{% endif %}

advert/templates/include/advert_list.html
{% load staticfiles %}



{% if advert.advert_active %}

    <div class="advert">
        <h5>
            <a href="{% url 'advert:one' advert.pk %}">
                {{ advert.advert_name }}
            </a>
        </h5>

{#        <a href="{% url 'advert:one' advert.pk %}">#}
{#            {% if  advert.advert_photo %}#}
{#                <img src="{{ advert.advert_thumbnail_240.url }}" alt="" class="img-responsive img-thumbnail">#}
{#            {% else %}#}
{#                <img src='http://placehold.it/240x130' alt="" class="img-responsive img-thumbnail">#}
{#            {% endif %}#}
{#        </a>#}



        <a href="{% url 'advert:one' advert.pk %}">
            <img src='http://placehold.it/240x130' alt="" class="img-responsive img-thumbnail">
        </a>



        <div class="icons-services">
            {% include 'include/advert_icons.html' %}
        </div>

        <div class="icons-info">
            <div class="row">
                <div class="col-lg-9 col-md-9 col-sm-9">
                    <p class="fa fa-money" aria-hidden="true" title="цена">&nbsp;
                        <span class="block-color">
                            {% if not advert.advert_price_to %}
                                {{ advert.advert_price_from }} грн.
                            {% else %}
                                от {{ advert.advert_price_from }}
                                до {{ advert.advert_price_to }} грн.
                            {% endif %}
                        </span>
                    </p>
                </div>

                {% if advert.advert_seat %}
                    <div class="col-lg-3 col-md-3 col-sm-3">
                        <p class="fa fa-bed" aria-hidden="true" title="спальных мест">
                            <span class="block-color">
                                {{ advert.advert_seat }}
                            </span>
                        </p>
                    </div>
                {% endif %}
            </div>

            <div title="объект недвижимости">
                <img class="for-rent" src="{% static 'icons/for-rent.svg' %}">
                <span class="block-color">
                    &nbsp;{{ advert.get_advert_property_type_display }}
                </span>
            </div>

            <div class="row">
                <div class="col-lg-9 col-md-9 col-sm-9 col-xs-10">
                    <p class="fa fa-calendar" aria-hidden="true" title="дата размещения">
                        <span class="block-color">
                            &nbsp; {{ advert.advert_date_pub|date:'d M Y'}}
                        </span>
                    </p>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-2" title="смотреть подробности">
                    <a href="{% url 'advert:one' advert.pk %}">
                        <p class="fa fa-angle-double-down"></p>
                    </a>
                </div>
            </div>

            {% if advert.advert_user == user %}
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 update-advert">
                        <a href="{% url 'advert:update' advert.pk %}" style="color: indianred">редактировать</a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>


{% endif %}