blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from blog.views import blog_one, add_comment
from blog.views import BlogAllView

urlpatterns = [
    url(r'^all/$', BlogAllView.as_view(), name='all'),
    url(r'^(?P<pk>[0-9]+)/$', blog_one, name='one'),
    url(r'^add_comment/(?P<pk>[0-9]+)$', add_comment, name='add_comment',)
]

rest_brd/urls.py
# -*- coding: utf-8 -*-
"""rest_brd URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin


from django.conf.urls import include, url
from django.contrib import admin
from auth.views import signup
from django.contrib.auth.views import login, logout
from advert.views import successful
from django.conf import settings
from django.conf.urls.static import static
from advert.views import AdvertCabinetView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^advert/', include('advert.urls', namespace='advert')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^signup/$', signup, name='signup'),
    url(r'^login/$', login, {'template_name': 'auth/login.html'}, name='login', ),
    url(r'^logout/$', logout, {'template_name': 'auth/logout.html', 'next_page': '/advert/all/'}, name='logout'),
    url(r'^cabinet/',  AdvertCabinetView.as_view(), name='cabinet'),
    # url(r'^photos/', include('photos.urls', namespace='photos')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone


class Blog(models.Model):
    class Meta:
        ordering = ['-blog_date_pub', 'blog_name']
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

    blog_name = models.CharField(max_length=100, verbose_name='название', )
    blog_content = models.TextField(verbose_name='текст статьи', blank=True, null=True, )
    blog_author = models.CharField(max_length=50, default='Viacheslav Kardash', verbose_name='автор', blank=True,
                                   null=True, )
    blog_date_pub = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name='дата пубикации', blank=True, null=True, )
    blog_date_update = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name='дата редактирования',
                                            blank=True, null=True, )
    blog_title = models.CharField(max_length=75, verbose_name='Title', blank=True, null=True, )
    blog_descriptions = models.TextField(max_length=200, verbose_name='Descriptions', blank=True, null=True, )
    blog_keywords = models.TextField(max_length=150, verbose_name='Keywords', blank=True, null=True, )
    blog_slug = models.SlugField(verbose_name='URL', blank=True, null=True, )

    def __unicode__(self):
        return self.blog_name


class Comments(models.Model):
    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'
        ordering = []

    comments_article = models.ForeignKey(Blog)
    comments_text = models.TextField(verbose_name='текст комментрия', max_length=10000)
    comments_pub_date = models.DateTimeField(default=timezone.now, verbose_name='дата публикации')

    def __unicode__(self):
        return self.comments_text

blog/forms.py
# -*- coding: utf-8 -*-


from django.forms import ModelForm
from blog.models import Comments


class CommentForm(ModelForm):
    class Meta:
        model = Comments
        fields = ['comments_text']

blog/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, render_to_response, redirect
from blog.models import Blog, Comments
from blog.forms import CommentForm
from django.views.generic.list import ListView
from django.template.context_processors import csrf


class BlogAllView(ListView):
    model = Blog
    paginate_by = 5
    template_name = 'blog_all.html'
    context_object_name = 'context_blog_all'
    queryset = Blog.objects.all()


def blog_one(request, pk=1):
    comment_form = CommentForm
    args = {}
    args.update(csrf(request))
    args['key_blog_one'] = Blog.objects.get(pk=pk)
    args['key_comments'] = Comments.objects.filter(comments_article_id=pk)
    args['form'] = comment_form
    return render_to_response('blog_one.html', args)


def add_comment(request, pk):
    if request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.comments_article = Blog.objects.get(pk=pk)
            form.save()
    return redirect('/blog/%s/' % pk)

blog/templates/blog_all.html
{% extends 'blog_main.html' %}
{% load staticfiles %}


{% block blog_all %}

            {% for i in context_blog_all %}
                <h1><a href="{% url 'blog:one' i.pk %}">{{ i.blog_name }}</a></h1>
                <p>{{ i.blog_content|safe|truncatechars_html:300 }}</p>
                <p><a href="{% url 'blog:one' i.pk %}">читать далее</a></p>
            {% endfor %}

{% endblock %}

blog/templates/blog_main.html
{% extends 'main.html' %}
{% load staticfiles %}

{% block content %}
    <div class="blog_main">
        <div class="container">
        <h1 style="text-align: center">Блог</h1>
            <div class="row">
                <div class="col-sm-9 col-md-8 col-lg-9">

                    {% block blog_one %}{% endblock %}
                    {% block blog_all %}{% endblock %}

                    <div class="pagination-large hidden-xs">
                        <div class="row">
                            <div class="col-lg-12">
                                {% include 'pagination.html' %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-3 col-md-4 col-lg-3">

                </div>

                <div class="pagination-small visible-xs">
                    <div class="row">
                        <div class="col-xs-12">
                            {% include 'pagination.html' %}
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog_one.html
{% extends 'blog_main.html' %}
{% load staticfiles %}
{% load crispy_forms_tags%}

{% block blog_one %}

            <h1>{{ key_blog_one.blog_name }}</h1>
            <p>{{ key_blog_one.blog_content }}</p>
            {% for comments in  key_comments%}
                <b>Текст комментария: </b>
                <p style="font-style: italic">{{ comments.comments_text }}</p>
                <b>дата публикации: </b>
                <p>{{ comments.comments_pub_date }}</p><br>
            {% endfor %}
            <p>{{ key_comments.comments_text }}</p>

            <form action="{% url 'blog:add_comment' key_blog_one.pk %}" method="post" class="form">
                {% csrf_token %}
                {{ form|crispy }}
                    <button type="submit" class="btn btn-warning">Добавить комментарий</button>

            </form>


{% endblock %}