advert/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from views import AdvertAllView, AdvertOneView, AdvertFilterPriceUPView, AdvertFilterPriceDownView, \
    AdvertFilterPropertyTypeUPView, AdvertFilterPropertyTypeDownView
from views import AdvertUpdateView, successful, AdvertCabinetView, clear_database, AdvertAddView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^all/$', AdvertAllView.as_view(), name='all'),
    url(r'^(?P<pk>\d+)/$', AdvertOneView.as_view(), name='one'),
    url(r'^clear/$', clear_database, name='clear_database'),
    url(r'^filter_price_up/$', AdvertFilterPriceUPView.as_view(), name='filter_price_up'),
    url(r'^filter_price_down/$', AdvertFilterPriceDownView.as_view(), name='filter_price_down'),
    url(r'^filter_property_type_up/$', AdvertFilterPropertyTypeUPView.as_view(), name='filter_property_type_up'),
    url(r'^filter_property_type_down/$', AdvertFilterPropertyTypeDownView.as_view(), name='filter_property_type_down'),
    url(r'^add/$', AdvertAddView.as_view(), name='add'),
    url(r'^update/(?P<pk>\d+)/$', AdvertUpdateView.as_view(), name='update'),
    url(r'^successful/',  successful, name='successful')
    # url(r'^add/$', AdvertAddView.as_view(), name='add'),

    # url(r'^add/$', model_form_upload, name='add'),
]

blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from blog.views import blog_one, add_comment
from blog.views import BlogAllView

urlpatterns = [
    url(r'^all/$', BlogAllView.as_view(), name='all'),
    url(r'^(?P<pk>[0-9]+)/$', blog_one, name='one'),
    url(r'^add_comment/(?P<pk>[0-9]+)$', add_comment, name='add_comment',)
]

rest_brd/urls.py
# -*- coding: utf-8 -*-
"""rest_brd URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin


from django.conf.urls import include, url
from django.contrib import admin
from auth.views import signup
from django.contrib.auth.views import login, logout
from advert.views import successful
from django.conf import settings
from django.conf.urls.static import static
from advert.views import AdvertCabinetView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^advert/', include('advert.urls', namespace='advert')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^signup/$', signup, name='signup'),
    url(r'^login/$', login, {'template_name': 'auth/login.html'}, name='login', ),
    url(r'^logout/$', logout, {'template_name': 'auth/logout.html', 'next_page': '/advert/all/'}, name='logout'),
    url(r'^cabinet/',  AdvertCabinetView.as_view(), name='cabinet'),
    # url(r'^photos/', include('photos.urls', namespace='photos')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" name="Viacheslav Kardash">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <title>Все объявления</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'my.css' %}">
</head>

<body>
    {% block header %}{% endblock %}
    {% block auth_main %}{% endblock %}
    {% block content %}{% endblock %}
    {% block footer %}{% endblock %}

    <script src="{% static 'jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block upload_ajax_js %}{% endblock %}
    {% block salvattore_js %}{% endblock %}
</body>
</html>

templates/footer.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8" http-equiv="Content-type" content="text/html" name="Viacheslav Kardash">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/header.html
{% load staticfiles %}

    <div class="header">
        <div class="container">
            <div class="row">
                <div class="row">
                    <div class="col-sm-10 col-md-10 col-lg-10 title">
                        <h1>{% block name_site %}Отдых в Бердянске{% endblock %}</h1>
                    </div>

                    <div class="col-sm-2 col-md-2 col-lg-2 user">
                        {% if user.username %}
                            <a href="{% url 'logout' %}">Выйти ({{ user.username }})</a>
                        {% else %}
                            <a href="{% url 'login' %}">Войти</a> |
                            <a href="{% url 'signup' %}">Регистрация</a>
                        {% endif %}
                    </div>
                </div>

                <nav class="navbar navbar-default" role="navigation">
                    <div class="container">

                        {# менюшка для малых экранов#}
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                    data-target="#Menu" aria-expanded="false">
                                <span class="sr-only">Toogle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a href="" class="navbar-brand">Logo</a>
                        </div>
                        {# end менюшка для малых экранов#}

                        {# менюшка для десктопов #}
                        <div class="collapse navbar-collapse" id="Menu">
                            <ul class="nav navbar-nav" role="menubar">
                                <li class="active">
                                    <a href="#">Главная <span class="sr-only"></span></a>
                                </li>
                                <li><a href="{% url 'blog:all' %}">Блог</a></li>
                                <li><a href="">Куда пойти</a></li>
                                <li><a href="">Контакты</a></li>
                                <li><a href="">Платные объявления</a></li>
                                <li><a href="{% url 'cabinet' %}">Кабинет</a></li>
                            </ul>
                        </div>
                        {# end менюшка для десктопов #}
                    </div>
                </nav>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="btn-group btn-group-justified">
                    <div class="btn-group left">
                        <a href="{% url 'advert:all' %}" class="">
                            <p>Найти объявление</p>
                        </a>
                    </div>
                    <div class="btn-group right">
                        <a href="{% url 'advert:add' %}" class="">
                            <p>Разместить объявление</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

templates/main.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block header %}{% include 'header.html' %}{% endblock %}

{% block content %}{% endblock %}


{% block footer %}{% endblock %}

templates/pagination.html
{% load staticfiles %}

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}