advert/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from views import AdvertAllView, AdvertOneView, AdvertFilterPriceUPView, AdvertFilterPriceDownView, \
    AdvertFilterPropertyTypeUPView, AdvertFilterPropertyTypeDownView
from views import AdvertUpdateView, successful, AdvertCabinetView, clear_database, AdvertAddView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^all/$', AdvertAllView.as_view(), name='all'),
    url(r'^(?P<pk>\d+)/$', AdvertOneView.as_view(), name='one'),
    url(r'^clear/$', clear_database, name='clear_database'),
    url(r'^filter_price_up/$', AdvertFilterPriceUPView.as_view(), name='filter_price_up'),
    url(r'^filter_price_down/$', AdvertFilterPriceDownView.as_view(), name='filter_price_down'),
    url(r'^filter_property_type_up/$', AdvertFilterPropertyTypeUPView.as_view(), name='filter_property_type_up'),
    url(r'^filter_property_type_down/$', AdvertFilterPropertyTypeDownView.as_view(), name='filter_property_type_down'),
    url(r'^add/$', AdvertAddView.as_view(), name='add'),
    url(r'^update/(?P<pk>\d+)/$', AdvertUpdateView.as_view(), name='update'),
    url(r'^successful/',  successful, name='successful')
    # url(r'^add/$', AdvertAddView.as_view(), name='add'),

    # url(r'^add/$', model_form_upload, name='add'),
]

blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from blog.views import blog_one, add_comment
from blog.views import BlogAllView

urlpatterns = [
    url(r'^all/$', BlogAllView.as_view(), name='all'),
    url(r'^(?P<pk>[0-9]+)/$', blog_one, name='one'),
    url(r'^add_comment/(?P<pk>[0-9]+)$', add_comment, name='add_comment',)
]

rest_brd/urls.py
# -*- coding: utf-8 -*-
"""rest_brd URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin


from django.conf.urls import include, url
from django.contrib import admin
from auth.views import signup
from django.contrib.auth.views import login, logout
from advert.views import successful
from django.conf import settings
from django.conf.urls.static import static
from advert.views import AdvertCabinetView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^advert/', include('advert.urls', namespace='advert')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^signup/$', signup, name='signup'),
    url(r'^login/$', login, {'template_name': 'auth/login.html'}, name='login', ),
    url(r'^logout/$', logout, {'template_name': 'auth/logout.html', 'next_page': '/advert/all/'}, name='logout'),
    url(r'^cabinet/',  AdvertCabinetView.as_view(), name='cabinet'),
    # url(r'^photos/', include('photos.urls', namespace='photos')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

advert/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from models import Advert, Photo



class AdvertForm(ModelForm):
    class Meta:
        model = Advert
        fields = ['advert_name',
                  'advert_content',
                  'advert_district',
                  'advert_property_type',
                  'advert_room',
                  'advert_seat',
                  'advert_price_from',
                  'advert_price_to',
                  'advert_address',
                  'advert_telephone',
                  'advert_conditioner',
                  'advert_tv',
                  'advert_shower',
                  'advert_wi_fi',
                  'advert_food',
                  'advert_animals',
                  'advert_parking',
                  'advert_balcony',
                  'advert_satellite_tv',
                  'advert_playground',
                  'advert_washer',
                  'advert_brazier',
                  'advert_author',
                  ]


# class PhotoForm(ModelForm):
#     class Meta:
#         model = Photo
#         fields = ['photo_origin']

class PhotoForm(ModelForm):
    class Meta:
        model = Photo
        fields = ['photo_origin']

advert/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render

from django.core.urlresolvers import reverse
from django.shortcuts import render, render_to_response, redirect
from advert.models import Advert, Photo
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormView
from django.views.generic.edit import UpdateView
from forms import AdvertForm, PhotoForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.db.models import F
from django.http import JsonResponse
from django.views import View
import time
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response


class AdvertAllView(ListView):
    model = Advert
    paginate_by = 9
    template_name = 'advert_all.html'
    context_object_name = 'context_advert_all'
    queryset = Advert.objects.all()


class AdvertFilterPriceUPView(ListView):
    model = Advert
    paginate_by = 9
    template_name = 'filters/advert_filter_price_up.html'
    context_object_name = 'context_advert_filter_price_up'
    queryset = Advert.objects.all().order_by('advert_price_from')


class AdvertFilterPriceDownView(ListView):
    model = Advert
    paginate_by = 9
    template_name = 'filters/advert_filter_price_down.html'
    context_object_name = 'context_advert_filter_price_down'
    queryset = Advert.objects.all().order_by('-advert_price_from')


class AdvertFilterPropertyTypeUPView(ListView):
    model = Advert
    paginate_by = 9
    template_name = 'filters/advert_filter_property_type_up.html'
    context_object_name = 'context_advert_filter_property_type_up'
    queryset = Advert.objects.all().order_by('advert_property_type')


class AdvertFilterPropertyTypeDownView(ListView):
    model = Advert
    paginate_by = 9
    template_name = 'filters/advert_filter_property_type_down.html'
    context_object_name = 'context_advert_filter_property_type_down'
    queryset = Advert.objects.all().order_by('-advert_property_type')


class AdvertOneView(DetailView):
    model = Advert
    template_name = 'advert_one.html'

    def get(self, request, *args, **kwargs):
        self.counter = Advert.objects.get(pk=self.kwargs['pk'])
        self.counter.advert_views = F('advert_views') + 1
        self.counter.save()
        return super(AdvertOneView, self).get(request, *args, **kwargs)


class AdvertCabinetView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    model = Advert
    template_name = 'cabinet.html'
    context_object_name = 'context_cabinet'
    paginate_by = 6

    def get_queryset(self):
        context = Advert.objects.filter(advert_user=self.request.user)
        return context


def successful(request):
    return render_to_response('successful.html')


class AdvertUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = Advert
    form_class = AdvertForm
    template_name = 'advert_update.html'

    def get_success_url(self):
        return reverse('advert:one', args=(self.kwargs['pk'],))

    def get_object(self, *args, **kwargs):
        object = super(AdvertUpdateView, self).get_object(*args, **kwargs)
        if object.advert_user != self.request.user:
            raise Http404
        return object


class AdvertAddView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    template_name = 'advert_add.html'
    form_class = AdvertForm
    success_url = ('/advert/successful/')

    def get_context_data(self, **kwargs):
        context = super(AdvertAddView, self).get_context_data(**kwargs)
        context['photo_origin'] = Photo.objects.all()
        return context

    # def post(self, request):
    #     time.sleep(1)
    #     form = PhotoForm(self.request.POST, self.request.FILES)
    #     if form.is_valid():
    #         photo = form.save()
    #         data = {'is_valid': True, 'name': photo.photo_origin.name, 'url': photo.photo_origin.url}
    #     else:
    #         data = {'is_valid': False}
    #     return JsonResponse(data)

    def form_valid(self, form):
        advert = form.save(commit=False)
        advert.advert_user = self.request.user
        advert = Advert(self.request.POST)
        advert = form.save()
        return super(AdvertAddView, self).form_valid(form)

    # def get(self, request):
    #     photos_list = Photo.objects.all()
    #     return render(self.request, 'advert_add.html', {'photos': photos_list})

    # def get(self, request):
    #     photos_list = Photo.objects.all()
    #     return render(self.request, 'advert_add.html', {'photos': photos_list})
    #
    # def post(self, request):
    #     time.sleep(1)
    #     form = PhotoForm(self.request.POST, self.request.FILES)
    #     if form.is_valid():
    #         photo = form.save()
    #         data = {'is_valid': True, 'name': photo.photo_origin.name, 'url': photo.photo_origin.url}
    #     else:
    #         data = {'is_valid': False}
    #     return JsonResponse(data)





# class AdvertPhotoAddView(LoginRequiredMixin, View):
#     login_url = '/login/'
#
#     def get(self, request):
#         photos_list = Photo.objects.all()
#         return render(self.request, 'advert_add_photo.html', {'photos': photos_list})
#
#     def post(self, request):
#         time.sleep(
#             1)  # You don't need this line. This is just to delay the process so you can see the progress bar testing locally.
#         form = PhotoForm(self.request.POST, self.request.FILES)
#         if form.is_valid():
#             photo = form.save()
#             data = {'is_valid': True, 'name': photo.photo_origin.name, 'url': photo.photo_origin.url}
#         else:
#             data = {'is_valid': False}
#         return JsonResponse(data)












# class AdvertPhotoAddView(LoginRequiredMixin, View):
#     login_url = '/login/'
#     def get(self, request):
#         photos_list = Photo.objects.all()
#         return render(self.request, 'advert_add.html', {'photos': photos_list})
#
#     def post(self, request):
#         time.sleep(1)  # You don't need this line. This is just to delay the process so you can see the progress bar testing locally.
#         form = PhotoForm(self.request.POST, self.request.FILES)
#         if form.is_valid():
#             photo = form.save()
#             data = {'is_valid': True, 'name': photo.photo_origin.name, 'url': photo.photo_origin.url}
#         else:
#             data = {'is_valid': False}
#         return JsonResponse(data)














def clear_database(request):
    for photo in Photo.objects.all():
        photo.photo_origin.delete()
        photo.delete()
    return redirect(request.POST.get('next'))














    # class AdvertAddView(LoginRequiredMixin, CreateView):
    #     context_object_name = 'advert_form'
    #     login_url = '/login/'
    #     template_name = 'advert_add.html'
    #     form_class = AdvertForm
    #     success_url = ('/advert/successful/')
    #
    #     def form_valid(self, form):
    #         advert = form.save(commit=False)
    #         advert.advert_user = self.request.user
    #         advert = Advert(self.request.POST)
    #         advert = form.save()
    #         return super(AdvertAddView, self).form_valid(form)


    # class PhotoAddView(LoginRequiredMixin, CreateView):
    #     login_url = '/login/'
    #     template_name = 'advert_add.html'
    #     form_class = PhotoForm
    #     success_url = ('/advert/successful/')
    #
    #     def form_valid(self, form):
    #         photo = form.save(commit=False)
    #         photo = Photo(self.request.POST, self.request.FILES)
    #         photo = form.save()
    #         return super(PhotoAddView, self).form_valid(form)


    # def model_form_upload(request):
    #     if request.method == 'POST':
    #         form = PhotoForm(request.POST, request.FILES)
    #         if form.is_valid():
    #             form.save()
    #             return redirect('/advert/all/')
    #     else:
    #         form = PhotoForm()
    #     return render(request, 'advert_add.html', {
    #         'form1': form
    #     })













    # class AdvertAddView(LoginRequiredMixin, CreateView):
    #     login_url = '/login/'
    #     template_name = 'advert_add.html'
    #     form_class = AdvertForm
    #     success_url = ('/advert/successful/')
    #
    #     def form_valid(self, form):
    #         advert = form.save(commit=False)
    #         advert.advert_user = self.request.user
    #         advert = Advert(self.request.POST, self.request.FILES)
    #         advert = form.save()
    #         return super(AdvertAddView, self).form_valid(form)
    #
    #





    # class AdvertAddView(LoginRequiredMixin, CreateView):
    #     login_url = '/login/'
    #     template_name = 'advert_add.html'
    #     form_class = AdvertForm
    #     success_url = ('/advert/successful/')
    #
    #     def form_valid(self, form):
    #         advert = form.save(commit=False)
    #         advert.advert_user = self.request.user
    #         advert = Advert(self.request.POST, self.request.FILES)
    #         advert = form.save()
    #         return super(AdvertAddView, self).form_valid(form)



























































































    # def cabinet(request):
    #     context = Advert.objects.all()[:8]
    #     return render_to_response('cabinet.html', {'context':context})




    # '/blog/details/%s/' % pk

    # def get(self, request, *args, **kwargs):
    #     self.context = Advert.objects.get(pk=self.kwargs['pk'])
    #     self.form = AdvertForm(instance=self.context)
    #     return super(AdvertUpdateView, self).get(request, *args, **kwargs)
    #
    # def form_valid(self, form):

advert/templates/advert_add.html
{% extends 'advert_main.html' %}
{% load staticfiles %}
{% load crispy_forms_tags%}



{% block advert_add %}

    <h2>Разместить объявление:</h2>
    <form action="" method="post" enctype="multipart/form-data"  >
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-default" >отправить</button>
    </form>

    <div style="margin-bottom: 20px;">
        <button type="button" class="btn btn-primary js-upload-photos">
            <span class="glyphicon glyphicon-cloud-upload"></span> Загрузить фото
        </button>
        <input id="fileupload"
               type="file"
               name="photo_origin"
               multiple style="display: none;"
               data-url="{% url 'advert:add' %}"
               data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
    </div>




    <table id="gallery" class="table table-bordered">
    <thead>
      <tr>
        <th>загруженные фото:</th>
      </tr>
    </thead>
    <tbody>
      {% for photo in photo_origin %}
        <tr>
          <td><a href="{{ photo.photo_origin.url }}">{{ photo.photo_origin.name }}</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

 <form method="post" action="{% url 'advert:clear_database' %}">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    <button type="submit" class="btn btn-danger pull-right">
      <span class="glyphicon glyphicon-trash"></span> Удалить фотографии
    </button>
    </form>




    <div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">загрузка...</h4>
                </div>

                <div class="modal-body">
                    <div class="progress progress-striped">
                        <div class="progress-bar progress-bar-info" role="progressbar" style="width: 0%;">0%</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block upload_ajax_js %}
    <script src="{% static 'upload_ajax/jquery.ui.widget.js' %}"></script>
    <script src="{% static 'upload_ajax/jquery.iframe-transport.js' %}"></script>
    <script src="{% static 'upload_ajax/jquery.fileupload.js' %}"></script>
    <script src="{% static 'upload_ajax/progress-bar-upload.js' %}"></script>
{% endblock %}

advert/templates/advert_all.html
{% extends 'advert_main.html' %}
{% load staticfiles %}

{% block advert_all %}
    {% for advert in context_advert_all %}
        {% include 'include/advert_list.html' %}
    {% endfor %}
{% endblock %}

{% block sidebar %}
    <p>
        <a href="{% url 'advert:filter_price_up' %}">сортировать по цене
            &nbsp;<span class="" aria-hidden="true"></span>
        </a>
    </p>
    <p>
        <a href="{% url 'advert:filter_property_type_up' %}">сортировать по типу
            &nbsp;<span class="" aria-hidden="true"></span>
        </a>
    </p>
{% endblock %}

advert/templates/advert_main.html
{% extends 'main.html' %}
{% load staticfiles %}


{% block content %}
    <div class="content">
        <div class="container">
            <h1 style="text-align: center">Объявления</h1>
            <div class="row main">
                <div class="col-sm-9 col-md-8 col-lg-9">
                    {% block advert_one %}{% endblock %}
                    {% block advert_add %}{% endblock %}
                    <div class="row masonry" data-columns>
                        {% block cabinet %}{% endblock %}
                        {% block advert_all %}{% endblock %}
                        {% block advert_price_up %}{% endblock %}
                        {% block advert_price_down %}{% endblock %}
                        {% block advert_property_type %}{% endblock %}
                    </div>

                    <div class="pagination-large hidden-xs">
                        <div class="row">
                            <div class="col-lg-12">
                                {% include 'pagination.html' %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-3 col-md-4 col-lg-3 sidebar">
                    <div class="filter">
                        {% if padinator.page_range != page_obj %}
                            <p id="filter">фильтр:</p>
                        {% endif %}

                        {% block sidebar %}{% endblock %}
                    </div>
                </div>

                <div class="pagination-small visible-xs">
                    <div class="row">
                        <div class="col-xs-12">
                            {% include 'pagination.html' %}
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}


{% block salvattore_js %}
    <script src="{% static 'salvattore/salvattore.min.js' %}"></script>
{% endblock %}



{#{% for i in paginator.page_range %}#}
{#      {% if page_obj.number == i %}#}
{#        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>#}
{#      {% else %}#}
{#        <li><a href="?page={{ i }}">{{ i }}</a></li>#}
{#      {% endif %}#}
{#    {% endfor %}#}














{##}
{#{% block content %}#}
{#    <div class="content">#}
{#        <div class="container">#}
{#        <h1>Объявления</h1>#}
{#            <div class="row main">#}
{#                <div class="col-lg-9 col-md-8 col-sm-9">#}
{#                    <div class="row masonry" data-columns>#}
{#                        {% block price %}{% endblock %}#}
{#                        {% block default %}{% endblock %}#}
{#                        {% block property_type %}{% endblock %}#}
{#                    </div>#}
{#                </div>#}
{##}
{#                <div class="col-lg-3 col-md-4 col-sm-3">#}
{##}
{#                {% block sidebar %}{% endblock %}#}
{##}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}

advert/templates/advert_one.html
{% extends 'advert_main.html' %}
{% load staticfiles %}

{% block advert_one %}
            <h1>{{ advert.advert_name }}</h1>
            <p>{{ advert.advert_content }}</p>
            {% include 'include/advert_icons.html' %}
            <p>{{ advert.advert_pub_date|date }}</p>
            <p>сейчас у нас {{ time_now }}</p>
            <p>просмотров - {{ advert.advert_views }}</p>
            <p>{{ advert.advert_user }}</p>

{#                {% if advert.advert_photo %}#}
{#                    {% if  advert.advert_thumbnail_350 %}#}
{#                        <a href="{{ advert.advert_photo.url }}">#}
{#                            <img src="{{ advert.advert_thumbnail_350.url }}" alt="фото">#}
{#                        </a>#}
{##}
{#                    {% endif %}#}
{#                {% endif %}#}





{% if advert.advert_user == user %}
  <a href="{% url 'advert:update' pk=object.pk %}">редактировать</a>
{% endif %}





{% endblock %}




{% block sidebar %}
    <p><a href="{% url 'advert:filter_price_up' %}">сортировать по цене</a></p>
    <p><a href="{% url 'advert:filter_property_type_up' %}">сортировать по району</a></p>
    <p><a href="{% url 'advert:all' %}">перейти ко всем</a></p>
{% endblock %}

advert/templates/advert_update.html
{% extends 'advert_main.html' %}
{% load staticfiles %}
{% load crispy_forms_tags%}


{% block advert_add %}
    <h2>Резместить объявление:</h2>
    <form action="" method="post" enctype="multipart/form-data"  >
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-default" >отправить</button>
    </form>

{% endblock %}

advert/templates/cabinet.html
{% extends 'advert_main.html' %}

{% block cabinet %}

    {% for advert in context_cabinet %}

on        {% include 'include/advert_list.html' %}

    {% endfor %}
    <h4><a href="{% url 'advert:all' %}">на главную</a></h4>
{% endblock %}


{% block sidebar %}
    <p>
        <a href="{% url 'advert:filter_price_up' %}">сортировать по цене
            &nbsp;<span class="fa fa-long-arrow-down" aria-hidden="true"></span>
        </a>
    </p>
    <p>
        <a href="{% url 'advert:filter_property_type_up' %}">сортировать по типу
            &nbsp;<span class="" aria-hidden="true"></span>
        </a>
    </p>
    <p><a href="{% url 'advert:all' %}">сбросить</a></p>
{% endblock %}

advert/templates/successful.html
{% load staticfiles %}

<div class="container" style="text-align: center">
    <div class="row">
        <h2>Объявление добавлено успешно. В течении суток оно появится на сайте</h2>
        <h3><a href="{% url 'advert:all' %}">вернуться на сайт</a></h3>
    </div>
</div>




<div class="message-id">
    <p>Ваше сообщение отправлено</p>
</div>